version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
    restart: always

  client:
    build: ./client
    ports:
      - "3000:80"
    restart: always

  admin:
    build: ./admin-panel
    ports:
      - "3001:80"
    restart: always
